package arm.node;

@:keep class FpsController extends armory.logicnode.LogicTree {

	var functionNodes:Map<String, armory.logicnode.FunctionNode>;

	var functionOutputNodes:Map<String, armory.logicnode.FunctionOutputNode>;

	public function new() {
		super();
		name = "FpsController";
		this.functionNodes = new Map();
		this.functionOutputNodes = new Map();
		notifyOnAdd(add);
	}

	override public function add() {
		var _SetObjectProperty_013 = new armory.logicnode.SetPropertyNode(this);
		var _Branch_003 = new armory.logicnode.BranchNode(this);
		var _OutputSequence = new armory.logicnode.SequenceNode(this);
		var _OnUpdate_002 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_002.property0 = "Update";
		_OnUpdate_002.addOutputs([_OutputSequence]);
		_OutputSequence.addInput(_OnUpdate_002, 0);
		var _Branch_002 = new armory.logicnode.BranchNode(this);
		_Branch_002.addInput(_OutputSequence, 0);
		var _GetObjectProperty_004 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_004.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectProperty_004.addInput(new armory.logicnode.StringNode(this, "isRunning"), 0);
		_GetObjectProperty_004.addOutputs([_Branch_002]);
		_GetObjectProperty_004.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Branch_002.addInput(_GetObjectProperty_004, 0);
		var _SetObjectProperty_011 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_011.addInput(_Branch_002, 0);
		_SetObjectProperty_011.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_011.addInput(new armory.logicnode.StringNode(this, "stamina"), 0);
		var _Clamp = new armory.logicnode.ClampNode(this);
		var _Math_001 = new armory.logicnode.MathNode(this);
		_Math_001.property0 = "Subtract";
		_Math_001.property1 = "false";
		var _GetObjectProperty_005 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_005.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectProperty_005.addInput(new armory.logicnode.StringNode(this, "stamina"), 0);
		_GetObjectProperty_005.addOutputs([_Math_001]);
		_GetObjectProperty_005.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Math_001.addInput(_GetObjectProperty_005, 0);
		_Math_001.addInput(new armory.logicnode.FloatNode(this, 0.3999999761581421), 0);
		_Math_001.addOutputs([_Clamp]);
		_Clamp.addInput(_Math_001, 0);
		_Clamp.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Clamp.addInput(new armory.logicnode.FloatNode(this, 100.0), 0);
		_Clamp.addOutputs([_SetObjectProperty_011]);
		_SetObjectProperty_011.addInput(_Clamp, 0);
		_SetObjectProperty_011.addOutputs([new armory.logicnode.NullNode(this)]);
		_Branch_002.addOutputs([_SetObjectProperty_011]);
		var _SetObjectProperty_012 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_012.addInput(_Branch_002, 1);
		_SetObjectProperty_012.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_012.addInput(new armory.logicnode.StringNode(this, "stamina"), 0);
		var _Clamp_001 = new armory.logicnode.ClampNode(this);
		var _Math_002 = new armory.logicnode.MathNode(this);
		_Math_002.property0 = "Add";
		_Math_002.property1 = "false";
		var _GetObjectProperty_006 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_006.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectProperty_006.addInput(new armory.logicnode.StringNode(this, "stamina"), 0);
		_GetObjectProperty_006.addOutputs([_Math_002]);
		_GetObjectProperty_006.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Math_002.addInput(_GetObjectProperty_006, 0);
		_Math_002.addInput(new armory.logicnode.FloatNode(this, 0.19999998807907104), 0);
		_Math_002.addOutputs([_Clamp_001]);
		_Clamp_001.addInput(_Math_002, 0);
		_Clamp_001.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Clamp_001.addInput(new armory.logicnode.FloatNode(this, 100.0), 0);
		_Clamp_001.addOutputs([_SetObjectProperty_012]);
		_SetObjectProperty_012.addInput(_Clamp_001, 0);
		_SetObjectProperty_012.addOutputs([new armory.logicnode.NullNode(this)]);
		_Branch_002.addOutputs([_SetObjectProperty_012]);
		_OutputSequence.addOutputs([_Branch_002]);
		_OutputSequence.addOutputs([_Branch_003]);
		_Branch_003.addInput(_OutputSequence, 1);
		var _Compare_001 = new armory.logicnode.CompareNode(this);
		_Compare_001.property0 = "Less";
		_Compare_001.property1 = 9.999999747378752e-05;
		var _GetObjectProperty_007 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_007.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectProperty_007.addInput(new armory.logicnode.StringNode(this, "stamina"), 0);
		_GetObjectProperty_007.addOutputs([_Compare_001]);
		_GetObjectProperty_007.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Compare_001.addInput(_GetObjectProperty_007, 0);
		var _Float_008 = new armory.logicnode.FloatNode(this);
		_Float_008.addInput(new armory.logicnode.FloatNode(this, 5.0), 0);
		_Float_008.addOutputs([_Compare_001]);
		_Compare_001.addInput(_Float_008, 0);
		_Compare_001.addOutputs([_Branch_003]);
		_Branch_003.addInput(_Compare_001, 0);
		_Branch_003.addOutputs([_SetObjectProperty_013]);
		_Branch_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetObjectProperty_013.addInput(_Branch_003, 0);
		_SetObjectProperty_013.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_013.addInput(new armory.logicnode.StringNode(this, "m_speed"), 0);
		var _Float_009 = new armory.logicnode.FloatNode(this);
		_Float_009.addInput(new armory.logicnode.FloatNode(this, 8.0), 0);
		_Float_009.addOutputs([_SetObjectProperty_013]);
		_SetObjectProperty_013.addInput(_Float_009, 0);
		_SetObjectProperty_013.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetObjectProperty_010 = new armory.logicnode.SetPropertyNode(this);
		var _SetObjectProperty_006 = new armory.logicnode.SetPropertyNode(this);
		var _Branch_001 = new armory.logicnode.BranchNode(this);
		var _Gate_002 = new armory.logicnode.GateNode(this);
		_Gate_002.property0 = "Equal";
		_Gate_002.property1 = 9.999999747378752e-05;
		var _Merge = new armory.logicnode.MergeNode(this);
		var _Keyboard_006 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_006.property0 = "down";
		_Keyboard_006.property1 = "w";
		_Keyboard_006.addOutputs([_Merge]);
		_Keyboard_006.addOutputs([new armory.logicnode.BooleanNode(this, false)]);
		_Merge.addInput(_Keyboard_006, 0);
		var _Keyboard_007 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_007.property0 = "down";
		_Keyboard_007.property1 = "s";
		_Keyboard_007.addOutputs([_Merge]);
		_Keyboard_007.addOutputs([new armory.logicnode.BooleanNode(this, false)]);
		_Merge.addInput(_Keyboard_007, 0);
		var _Keyboard_008 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_008.property0 = "down";
		_Keyboard_008.property1 = "a";
		_Keyboard_008.addOutputs([_Merge]);
		_Keyboard_008.addOutputs([new armory.logicnode.BooleanNode(this, false)]);
		_Merge.addInput(_Keyboard_008, 0);
		var _Keyboard_009 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_009.property0 = "down";
		_Keyboard_009.property1 = "d";
		_Keyboard_009.addOutputs([_Merge]);
		_Keyboard_009.addOutputs([new armory.logicnode.BooleanNode(this, false)]);
		_Merge.addInput(_Keyboard_009, 0);
		_Merge.addOutputs([_Gate_002]);
		_Gate_002.addInput(_Merge, 0);
		var _Keyboard_010 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_010.property0 = "down";
		_Keyboard_010.property1 = "shift";
		_Keyboard_010.addOutputs([new armory.logicnode.NullNode(this)]);
		_Keyboard_010.addOutputs([_Gate_002]);
		_Gate_002.addInput(_Keyboard_010, 1);
		var _Boolean_006 = new armory.logicnode.BooleanNode(this);
		_Boolean_006.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_Boolean_006.addOutputs([_Gate_002]);
		_Gate_002.addInput(_Boolean_006, 0);
		_Gate_002.addOutputs([_Branch_001]);
		_Gate_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_Branch_001.addInput(_Gate_002, 0);
		var _Compare = new armory.logicnode.CompareNode(this);
		_Compare.property0 = "Greater";
		_Compare.property1 = 9.999999747378752e-05;
		var _GetObjectProperty_003 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_003.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectProperty_003.addInput(new armory.logicnode.StringNode(this, "stamina"), 0);
		_GetObjectProperty_003.addOutputs([_Compare]);
		_GetObjectProperty_003.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Compare.addInput(_GetObjectProperty_003, 0);
		var _Float_005 = new armory.logicnode.FloatNode(this);
		_Float_005.addInput(new armory.logicnode.FloatNode(this, 5.0), 0);
		_Float_005.addOutputs([_Compare]);
		_Compare.addInput(_Float_005, 0);
		_Compare.addOutputs([_Branch_001]);
		_Branch_001.addInput(_Compare, 0);
		_Branch_001.addOutputs([_SetObjectProperty_006]);
		_Branch_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetObjectProperty_006.addInput(_Branch_001, 0);
		_SetObjectProperty_006.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_006.addInput(new armory.logicnode.StringNode(this, "m_speed"), 0);
		var _Float_006 = new armory.logicnode.FloatNode(this);
		_Float_006.addInput(new armory.logicnode.FloatNode(this, 12.0), 0);
		_Float_006.addOutputs([_SetObjectProperty_006]);
		_SetObjectProperty_006.addInput(_Float_006, 0);
		_SetObjectProperty_006.addOutputs([_SetObjectProperty_010]);
		_SetObjectProperty_010.addInput(_SetObjectProperty_006, 0);
		_SetObjectProperty_010.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_010.addInput(new armory.logicnode.StringNode(this, "isRunning"), 0);
		var _Boolean_005 = new armory.logicnode.BooleanNode(this);
		_Boolean_005.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_Boolean_005.addOutputs([_SetObjectProperty_010]);
		_SetObjectProperty_010.addInput(_Boolean_005, 0);
		_SetObjectProperty_010.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetObjectProperty_007 = new armory.logicnode.SetPropertyNode(this);
		var _OnInit_001 = new armory.logicnode.OnInitNode(this);
		var _SetObjectProperty_003 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_003.addInput(_OnInit_001, 0);
		_SetObjectProperty_003.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_003.addInput(new armory.logicnode.StringNode(this, "m_speed"), 0);
		var _Float = new armory.logicnode.FloatNode(this);
		_Float.addInput(new armory.logicnode.FloatNode(this, 8.0), 0);
		_Float.addOutputs([_SetObjectProperty_003]);
		_SetObjectProperty_003.addInput(_Float, 0);
		_SetObjectProperty_003.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetObjectProperty_004 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_004.addInput(_OnInit_001, 0);
		_SetObjectProperty_004.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_004.addInput(new armory.logicnode.StringNode(this, "stamina"), 0);
		var _Float_004 = new armory.logicnode.FloatNode(this);
		_Float_004.addInput(new armory.logicnode.FloatNode(this, 100.0), 0);
		_Float_004.addOutputs([_SetObjectProperty_004]);
		_SetObjectProperty_004.addInput(_Float_004, 0);
		_SetObjectProperty_004.addOutputs([new armory.logicnode.NullNode(this)]);
		_OnInit_001.addOutputs([_SetObjectProperty_003, _SetObjectProperty_004, _SetObjectProperty_007]);
		_SetObjectProperty_007.addInput(_OnInit_001, 0);
		_SetObjectProperty_007.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_007.addInput(new armory.logicnode.StringNode(this, "isRunning"), 0);
		var _Boolean_003 = new armory.logicnode.BooleanNode(this);
		_Boolean_003.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_Boolean_003.addOutputs([_SetObjectProperty_007]);
		_SetObjectProperty_007.addInput(_Boolean_003, 0);
		_SetObjectProperty_007.addOutputs([new armory.logicnode.NullNode(this)]);
		var _OnUpdate_003 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_003.property0 = "Update";
		_OnUpdate_003.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetObjectProperty_009 = new armory.logicnode.SetPropertyNode(this);
		var _SetObjectProperty_008 = new armory.logicnode.SetPropertyNode(this);
		var _Keyboard_005 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_005.property0 = "released";
		_Keyboard_005.property1 = "shift";
		_Keyboard_005.addOutputs([_SetObjectProperty_008]);
		_Keyboard_005.addOutputs([new armory.logicnode.BooleanNode(this, false)]);
		_SetObjectProperty_008.addInput(_Keyboard_005, 0);
		_SetObjectProperty_008.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_008.addInput(new armory.logicnode.StringNode(this, "m_speed"), 0);
		var _Float_007 = new armory.logicnode.FloatNode(this);
		_Float_007.addInput(new armory.logicnode.FloatNode(this, 8.0), 0);
		_Float_007.addOutputs([_SetObjectProperty_008]);
		_SetObjectProperty_008.addInput(_Float_007, 0);
		_SetObjectProperty_008.addOutputs([_SetObjectProperty_009]);
		_SetObjectProperty_009.addInput(_SetObjectProperty_008, 0);
		_SetObjectProperty_009.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_009.addInput(new armory.logicnode.StringNode(this, "isRunning"), 0);
		var _Boolean_004 = new armory.logicnode.BooleanNode(this);
		_Boolean_004.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_Boolean_004.addOutputs([_SetObjectProperty_009]);
		_SetObjectProperty_009.addInput(_Boolean_004, 0);
		_SetObjectProperty_009.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetObjectRotation_001 = new armory.logicnode.SetRotationNode(this);
		_SetObjectRotation_001.property0 = "Euler Angles";
		var _Gate_001 = new armory.logicnode.GateNode(this);
		_Gate_001.property0 = "Less Equal";
		_Gate_001.property1 = 9.999999747378752e-05;
		var _OnUpdate_001 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_001.property0 = "Update";
		var _Gate = new armory.logicnode.GateNode(this);
		_Gate.property0 = "Greater Equal";
		_Gate.property1 = 9.999999747378752e-05;
		_Gate.addInput(_OnUpdate_001, 0);
		var _SeparateXYZ = new armory.logicnode.SeparateVectorNode(this);
		var _GetObjectRotation = new armory.logicnode.GetRotationNode(this);
		_GetObjectRotation.addInput(new armory.logicnode.ObjectNode(this, "CameraOrigin"), 0);
		var _SeparateXYZ_001 = new armory.logicnode.SeparateVectorNode(this);
		_SeparateXYZ_001.addInput(_GetObjectRotation, 0);
		_SeparateXYZ_001.addOutputs([_Gate_001]);
		var _Vector_003 = new armory.logicnode.VectorNode(this);
		var _Float_003 = new armory.logicnode.FloatNode(this);
		_Float_003.addInput(new armory.logicnode.FloatNode(this, -1.5), 0);
		_Float_003.addOutputs([_Gate_001, _Vector_003]);
		_Vector_003.addInput(_Float_003, 0);
		_Vector_003.addInput(_SeparateXYZ_001, 1);
		_Vector_003.addInput(_SeparateXYZ_001, 2);
		_Vector_003.addOutputs([_SetObjectRotation_001]);
		_SeparateXYZ_001.addOutputs([_Vector_003]);
		_SeparateXYZ_001.addOutputs([_Vector_003]);
		_GetObjectRotation.addOutputs([_SeparateXYZ, _SeparateXYZ_001]);
		_GetObjectRotation.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_GetObjectRotation.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_GetObjectRotation.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_GetObjectRotation.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_GetObjectRotation.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ.addInput(_GetObjectRotation, 0);
		_SeparateXYZ.addOutputs([_Gate]);
		var _Vector_002 = new armory.logicnode.VectorNode(this);
		var _Float_002 = new armory.logicnode.FloatNode(this);
		_Float_002.addInput(new armory.logicnode.FloatNode(this, 1.5), 0);
		_Float_002.addOutputs([_Gate, _Vector_002]);
		_Vector_002.addInput(_Float_002, 0);
		_Vector_002.addInput(_SeparateXYZ, 1);
		_Vector_002.addInput(_SeparateXYZ, 2);
		var _SetObjectRotation = new armory.logicnode.SetRotationNode(this);
		_SetObjectRotation.property0 = "Euler Angles";
		_SetObjectRotation.addInput(_Gate, 0);
		_SetObjectRotation.addInput(new armory.logicnode.ObjectNode(this, "CameraOrigin"), 0);
		_SetObjectRotation.addInput(_Vector_002, 0);
		_SetObjectRotation.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_SetObjectRotation.addOutputs([new armory.logicnode.NullNode(this)]);
		_Vector_002.addOutputs([_SetObjectRotation]);
		_SeparateXYZ.addOutputs([_Vector_002]);
		_SeparateXYZ.addOutputs([_Vector_002]);
		_Gate.addInput(_SeparateXYZ, 0);
		_Gate.addInput(_Float_002, 0);
		_Gate.addOutputs([_SetObjectRotation]);
		_Gate.addOutputs([new armory.logicnode.NullNode(this)]);
		_OnUpdate_001.addOutputs([_Gate, _Gate_001]);
		_Gate_001.addInput(_OnUpdate_001, 0);
		_Gate_001.addInput(_SeparateXYZ_001, 0);
		_Gate_001.addInput(_Float_003, 0);
		_Gate_001.addOutputs([_SetObjectRotation_001]);
		_Gate_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetObjectRotation_001.addInput(_Gate_001, 0);
		_SetObjectRotation_001.addInput(new armory.logicnode.ObjectNode(this, "CameraOrigin"), 0);
		_SetObjectRotation_001.addInput(_Vector_003, 0);
		_SetObjectRotation_001.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_SetObjectRotation_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _RotateObject = new armory.logicnode.RotateObjectNode(this);
		_RotateObject.property0 = "Euler Angles";
		var _Branch = new armory.logicnode.BranchNode(this);
		var _OnUpdate = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate.property0 = "Update";
		_OnUpdate.addOutputs([_Branch]);
		_Branch.addInput(_OnUpdate, 0);
		var _GetObjectProperty = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectProperty.addInput(new armory.logicnode.StringNode(this, "isLocked"), 0);
		_GetObjectProperty.addOutputs([_Branch]);
		_GetObjectProperty.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Branch.addInput(_GetObjectProperty, 0);
		var _RotateObject_001 = new armory.logicnode.RotateObjectNode(this);
		_RotateObject_001.property0 = "Euler Angles";
		_RotateObject_001.addInput(_Branch, 0);
		_RotateObject_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		var _Vector_001 = new armory.logicnode.VectorNode(this);
		_Vector_001.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector_001.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		var _GetMouseMovement = new armory.logicnode.GetMouseMovementNode(this);
		var _Math = new armory.logicnode.MathNode(this);
		_Math.property0 = "Multiply";
		_Math.property1 = "false";
		var _Float_001 = new armory.logicnode.FloatNode(this);
		_Float_001.addInput(new armory.logicnode.FloatNode(this, -0.05000000074505806), 0);
		_Float_001.addOutputs([_Math]);
		_Math.addInput(_Float_001, 0);
		var _GetApplicationTime = new armory.logicnode.TimeNode(this);
		_GetApplicationTime.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_GetApplicationTime.addOutputs([_Math]);
		_Math.addInput(_GetApplicationTime, 1);
		_Math.addOutputs([_GetMouseMovement, _GetMouseMovement]);
		_GetMouseMovement.addInput(_Math, 0);
		_GetMouseMovement.addInput(_Math, 0);
		_GetMouseMovement.addInput(new armory.logicnode.FloatNode(this, -1.0), 0);
		_GetMouseMovement.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_GetMouseMovement.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_GetMouseMovement.addOutputs([_Vector_001]);
		var _Vector = new armory.logicnode.VectorNode(this);
		_Vector.addInput(_GetMouseMovement, 3);
		_Vector.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector.addOutputs([_RotateObject]);
		_GetMouseMovement.addOutputs([_Vector]);
		_GetMouseMovement.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_GetMouseMovement.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Vector_001.addInput(_GetMouseMovement, 2);
		_Vector_001.addOutputs([_RotateObject_001]);
		_RotateObject_001.addInput(_Vector_001, 0);
		_RotateObject_001.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_RotateObject_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Branch.addOutputs([_RotateObject, _RotateObject_001]);
		_Branch.addOutputs([new armory.logicnode.NullNode(this)]);
		_RotateObject.addInput(_Branch, 0);
		_RotateObject.addInput(new armory.logicnode.ObjectNode(this, "CameraOrigin"), 0);
		_RotateObject.addInput(_Vector, 0);
		_RotateObject.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_RotateObject.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetObjectProperty = new armory.logicnode.SetPropertyNode(this);
		var _OnInit = new armory.logicnode.OnInitNode(this);
		_OnInit.addOutputs([_SetObjectProperty]);
		_SetObjectProperty.addInput(_OnInit, 0);
		_SetObjectProperty.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty.addInput(new armory.logicnode.StringNode(this, "isLocked"), 0);
		var _Boolean = new armory.logicnode.BooleanNode(this);
		_Boolean.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_Boolean.addOutputs([_SetObjectProperty]);
		_SetObjectProperty.addInput(_Boolean, 0);
		_SetObjectProperty.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetObjectProperty_001 = new armory.logicnode.SetPropertyNode(this);
		var _SetCursorState = new armory.logicnode.SetCursorStateNode(this);
		_SetCursorState.property0 = "hide locked";
		var _AlternateOutput = new armory.logicnode.AlternateNode(this);
		var _Mouse = new armory.logicnode.MergedMouseNode(this);
		_Mouse.property0 = "started";
		_Mouse.property1 = "right";
		_Mouse.addOutputs([_AlternateOutput]);
		_Mouse.addOutputs([new armory.logicnode.BooleanNode(this, false)]);
		_AlternateOutput.addInput(_Mouse, 0);
		_AlternateOutput.addOutputs([_SetCursorState]);
		var _SetCursorState_001 = new armory.logicnode.SetCursorStateNode(this);
		_SetCursorState_001.property0 = "hide locked";
		_SetCursorState_001.addInput(_AlternateOutput, 1);
		_SetCursorState_001.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		var _SetObjectProperty_002 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_002.addInput(_SetCursorState_001, 0);
		_SetObjectProperty_002.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_002.addInput(new armory.logicnode.StringNode(this, "isLocked"), 0);
		var _Boolean_002 = new armory.logicnode.BooleanNode(this);
		_Boolean_002.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_Boolean_002.addOutputs([_SetObjectProperty_002]);
		_SetObjectProperty_002.addInput(_Boolean_002, 0);
		_SetObjectProperty_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetCursorState_001.addOutputs([_SetObjectProperty_002]);
		_AlternateOutput.addOutputs([_SetCursorState_001]);
		_SetCursorState.addInput(_AlternateOutput, 0);
		_SetCursorState.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_SetCursorState.addOutputs([_SetObjectProperty_001]);
		_SetObjectProperty_001.addInput(_SetCursorState, 0);
		_SetObjectProperty_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_001.addInput(new armory.logicnode.StringNode(this, "isLocked"), 0);
		var _Boolean_001 = new armory.logicnode.BooleanNode(this);
		_Boolean_001.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_Boolean_001.addOutputs([_SetObjectProperty_001]);
		_SetObjectProperty_001.addInput(_Boolean_001, 0);
		_SetObjectProperty_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetObjectProperty_005 = new armory.logicnode.SetPropertyNode(this);
		var _OnInit_002 = new armory.logicnode.OnInitNode(this);
		_OnInit_002.addOutputs([_SetObjectProperty_005]);
		_SetObjectProperty_005.addInput(_OnInit_002, 0);
		_SetObjectProperty_005.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_005.addInput(new armory.logicnode.StringNode(this, "isGrounded"), 0);
		var _Boolean_007 = new armory.logicnode.BooleanNode(this);
		_Boolean_007.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_Boolean_007.addOutputs([_SetObjectProperty_005]);
		_SetObjectProperty_005.addInput(_Boolean_007, 0);
		_SetObjectProperty_005.addOutputs([new armory.logicnode.NullNode(this)]);
		var _ApplyImpulse = new armory.logicnode.ApplyImpulseNode(this);
		var _Branch_005 = new armory.logicnode.BranchNode(this);
		var _Keyboard_004 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_004.property0 = "started";
		_Keyboard_004.property1 = "space";
		_Keyboard_004.addOutputs([_Branch_005]);
		_Keyboard_004.addOutputs([new armory.logicnode.BooleanNode(this, false)]);
		_Branch_005.addInput(_Keyboard_004, 0);
		var _GetObjectProperty_001 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectProperty_001.addInput(new armory.logicnode.StringNode(this, "isGrounded"), 0);
		_GetObjectProperty_001.addOutputs([_Branch_005]);
		_GetObjectProperty_001.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Branch_005.addInput(_GetObjectProperty_001, 0);
		_Branch_005.addOutputs([_ApplyImpulse]);
		_Branch_005.addOutputs([new armory.logicnode.NullNode(this)]);
		_ApplyImpulse.addInput(_Branch_005, 0);
		_ApplyImpulse.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_ApplyImpulse.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 15.0), 0);
		_ApplyImpulse.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_ApplyImpulse.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetObjectProperty_016 = new armory.logicnode.SetPropertyNode(this);
		var _OutputSequence_001 = new armory.logicnode.SequenceNode(this);
		var _OnUpdate_005 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_005.property0 = "Update";
		_OnUpdate_005.addOutputs([_OutputSequence_001]);
		_OutputSequence_001.addInput(_OnUpdate_005, 0);
		_OutputSequence_001.addOutputs([_SetObjectProperty_016]);
		var _Gate_003 = new armory.logicnode.GateNode(this);
		_Gate_003.property0 = "Equal";
		_Gate_003.property1 = 9.999999747378752e-05;
		_Gate_003.addInput(_OutputSequence_001, 1);
		var _Keyboard_011 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_011.property0 = "down";
		_Keyboard_011.property1 = "w";
		_Keyboard_011.addOutputs([new armory.logicnode.NullNode(this)]);
		_Keyboard_011.addOutputs([_Gate_003]);
		_Gate_003.addInput(_Keyboard_011, 1);
		var _Boolean_010 = new armory.logicnode.BooleanNode(this);
		_Boolean_010.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_Boolean_010.addOutputs([_Gate_003]);
		_Gate_003.addInput(_Boolean_010, 0);
		var _SetObjectProperty_017 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_017.addInput(_Gate_003, 0);
		_SetObjectProperty_017.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_017.addInput(new armory.logicnode.StringNode(this, "dir"), 0);
		var _VectorMath_009 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_009.property0 = "Add";
		_VectorMath_009.property1 = false;
		var _GetObjectProperty_009 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_009.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectProperty_009.addInput(new armory.logicnode.StringNode(this, "dir"), 0);
		_GetObjectProperty_009.addOutputs([_VectorMath_009]);
		_GetObjectProperty_009.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_VectorMath_009.addInput(_GetObjectProperty_009, 0);
		_VectorMath_009.addInput(new armory.logicnode.VectorNode(this, 0.0, 1.0, 0.0), 0);
		_VectorMath_009.addOutputs([_SetObjectProperty_017]);
		_SetObjectProperty_017.addInput(_VectorMath_009, 0);
		_SetObjectProperty_017.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_003.addOutputs([_SetObjectProperty_017]);
		_Gate_003.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Gate_004 = new armory.logicnode.GateNode(this);
		_Gate_004.property0 = "Equal";
		_Gate_004.property1 = 9.999999747378752e-05;
		_Gate_004.addInput(_OutputSequence_001, 1);
		var _Keyboard_012 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_012.property0 = "down";
		_Keyboard_012.property1 = "s";
		_Keyboard_012.addOutputs([new armory.logicnode.NullNode(this)]);
		_Keyboard_012.addOutputs([_Gate_004]);
		_Gate_004.addInput(_Keyboard_012, 1);
		var _Boolean_011 = new armory.logicnode.BooleanNode(this);
		_Boolean_011.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_Boolean_011.addOutputs([_Gate_004]);
		_Gate_004.addInput(_Boolean_011, 0);
		var _SetObjectProperty_018 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_018.addInput(_Gate_004, 0);
		_SetObjectProperty_018.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_018.addInput(new armory.logicnode.StringNode(this, "dir"), 0);
		var _VectorMath_010 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_010.property0 = "Add";
		_VectorMath_010.property1 = false;
		var _GetObjectProperty_010 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_010.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectProperty_010.addInput(new armory.logicnode.StringNode(this, "dir"), 0);
		_GetObjectProperty_010.addOutputs([_VectorMath_010]);
		_GetObjectProperty_010.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_VectorMath_010.addInput(_GetObjectProperty_010, 0);
		_VectorMath_010.addInput(new armory.logicnode.VectorNode(this, 0.0, -1.0, 0.0), 0);
		_VectorMath_010.addOutputs([_SetObjectProperty_018]);
		_SetObjectProperty_018.addInput(_VectorMath_010, 0);
		_SetObjectProperty_018.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_004.addOutputs([_SetObjectProperty_018]);
		_Gate_004.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Gate_005 = new armory.logicnode.GateNode(this);
		_Gate_005.property0 = "Equal";
		_Gate_005.property1 = 9.999999747378752e-05;
		_Gate_005.addInput(_OutputSequence_001, 1);
		var _Keyboard_013 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_013.property0 = "down";
		_Keyboard_013.property1 = "a";
		_Keyboard_013.addOutputs([new armory.logicnode.NullNode(this)]);
		_Keyboard_013.addOutputs([_Gate_005]);
		_Gate_005.addInput(_Keyboard_013, 1);
		var _Boolean_013 = new armory.logicnode.BooleanNode(this);
		_Boolean_013.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_Boolean_013.addOutputs([_Gate_005]);
		_Gate_005.addInput(_Boolean_013, 0);
		var _SetObjectProperty_020 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_020.addInput(_Gate_005, 0);
		_SetObjectProperty_020.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_020.addInput(new armory.logicnode.StringNode(this, "dir"), 0);
		var _VectorMath_011 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_011.property0 = "Add";
		_VectorMath_011.property1 = false;
		var _GetObjectProperty_011 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_011.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectProperty_011.addInput(new armory.logicnode.StringNode(this, "dir"), 0);
		_GetObjectProperty_011.addOutputs([_VectorMath_011]);
		_GetObjectProperty_011.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_VectorMath_011.addInput(_GetObjectProperty_011, 0);
		_VectorMath_011.addInput(new armory.logicnode.VectorNode(this, -1.0, 0.0, 0.0), 0);
		_VectorMath_011.addOutputs([_SetObjectProperty_020]);
		_SetObjectProperty_020.addInput(_VectorMath_011, 0);
		_SetObjectProperty_020.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_005.addOutputs([_SetObjectProperty_020]);
		_Gate_005.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Gate_006 = new armory.logicnode.GateNode(this);
		_Gate_006.property0 = "Equal";
		_Gate_006.property1 = 9.999999747378752e-05;
		_Gate_006.addInput(_OutputSequence_001, 1);
		var _Keyboard_014 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_014.property0 = "down";
		_Keyboard_014.property1 = "d";
		_Keyboard_014.addOutputs([new armory.logicnode.NullNode(this)]);
		_Keyboard_014.addOutputs([_Gate_006]);
		_Gate_006.addInput(_Keyboard_014, 1);
		var _Boolean_012 = new armory.logicnode.BooleanNode(this);
		_Boolean_012.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_Boolean_012.addOutputs([_Gate_006]);
		_Gate_006.addInput(_Boolean_012, 0);
		var _SetObjectProperty_019 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_019.addInput(_Gate_006, 0);
		_SetObjectProperty_019.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_019.addInput(new armory.logicnode.StringNode(this, "dir"), 0);
		var _VectorMath_012 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_012.property0 = "Add";
		_VectorMath_012.property1 = false;
		var _GetObjectProperty_012 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_012.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectProperty_012.addInput(new armory.logicnode.StringNode(this, "dir"), 0);
		_GetObjectProperty_012.addOutputs([_VectorMath_012]);
		_GetObjectProperty_012.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_VectorMath_012.addInput(_GetObjectProperty_012, 0);
		_VectorMath_012.addInput(new armory.logicnode.VectorNode(this, 1.0, 0.0, 0.0), 0);
		_VectorMath_012.addOutputs([_SetObjectProperty_019]);
		_SetObjectProperty_019.addInput(_VectorMath_012, 0);
		_SetObjectProperty_019.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_006.addOutputs([_SetObjectProperty_019]);
		_Gate_006.addOutputs([new armory.logicnode.NullNode(this)]);
		_OutputSequence_001.addOutputs([_Gate_003, _Gate_004, _Gate_005, _Gate_006]);
		var _SetObjectProperty_021 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_021.addInput(_OutputSequence_001, 2);
		_SetObjectProperty_021.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_021.addInput(new armory.logicnode.StringNode(this, "dir"), 0);
		var _VectorMath = new armory.logicnode.VectorMathNode(this);
		_VectorMath.property0 = "Normalize";
		_VectorMath.property1 = false;
		var _GetObjectProperty_002 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_002.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectProperty_002.addInput(new armory.logicnode.StringNode(this, "dir"), 0);
		_GetObjectProperty_002.addOutputs([_VectorMath]);
		_GetObjectProperty_002.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_VectorMath.addInput(_GetObjectProperty_002, 0);
		_VectorMath.addOutputs([_SetObjectProperty_021]);
		_SetObjectProperty_021.addInput(_VectorMath, 0);
		var _SetRBVelocity = new armory.logicnode.SetVelocityNode(this);
		_SetRBVelocity.addInput(_SetObjectProperty_021, 0);
		_SetRBVelocity.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		var _Vector_005 = new armory.logicnode.VectorNode(this);
		var _SeparateXYZ_004 = new armory.logicnode.SeparateVectorNode(this);
		var _VectorMath_004 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_004.property0 = "MultiplyFloats";
		_VectorMath_004.property1 = false;
		var _VectorMath_003 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_003.property0 = "Add";
		_VectorMath_003.property1 = false;
		var _VectorMath_001 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_001.property0 = "MultiplyFloats";
		_VectorMath_001.property1 = false;
		var _TransformtoVector = new armory.logicnode.VectorFromTransformNode(this);
		_TransformtoVector.property0 = "Look";
		var _GetObjectTransform = new armory.logicnode.GetTransformNode(this);
		_GetObjectTransform.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		var _TransformtoVector_001 = new armory.logicnode.VectorFromTransformNode(this);
		_TransformtoVector_001.property0 = "Right";
		_TransformtoVector_001.addInput(_GetObjectTransform, 0);
		var _VectorMath_002 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_002.property0 = "MultiplyFloats";
		_VectorMath_002.property1 = false;
		_VectorMath_002.addInput(_TransformtoVector_001, 0);
		var _SeparateXYZ_003 = new armory.logicnode.SeparateVectorNode(this);
		var _GetObjectProperty_014 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_014.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectProperty_014.addInput(new armory.logicnode.StringNode(this, "dir"), 0);
		_GetObjectProperty_014.addOutputs([_SeparateXYZ_003]);
		_GetObjectProperty_014.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_SeparateXYZ_003.addInput(_GetObjectProperty_014, 0);
		_SeparateXYZ_003.addOutputs([_VectorMath_002]);
		_SeparateXYZ_003.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_003.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_VectorMath_002.addInput(_SeparateXYZ_003, 0);
		_VectorMath_002.addOutputs([_VectorMath_003]);
		_TransformtoVector_001.addOutputs([_VectorMath_002]);
		_TransformtoVector_001.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_TransformtoVector_001.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_GetObjectTransform.addOutputs([_TransformtoVector, _TransformtoVector_001]);
		_TransformtoVector.addInput(_GetObjectTransform, 0);
		_TransformtoVector.addOutputs([_VectorMath_001]);
		_TransformtoVector.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_TransformtoVector.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_VectorMath_001.addInput(_TransformtoVector, 0);
		var _SeparateXYZ_002 = new armory.logicnode.SeparateVectorNode(this);
		var _GetObjectProperty_013 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_013.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectProperty_013.addInput(new armory.logicnode.StringNode(this, "dir"), 0);
		_GetObjectProperty_013.addOutputs([_SeparateXYZ_002]);
		_GetObjectProperty_013.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_SeparateXYZ_002.addInput(_GetObjectProperty_013, 0);
		_SeparateXYZ_002.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_002.addOutputs([_VectorMath_001]);
		_SeparateXYZ_002.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_VectorMath_001.addInput(_SeparateXYZ_002, 1);
		_VectorMath_001.addOutputs([_VectorMath_003]);
		_VectorMath_003.addInput(_VectorMath_001, 0);
		_VectorMath_003.addInput(_VectorMath_002, 0);
		_VectorMath_003.addOutputs([_VectorMath_004]);
		_VectorMath_004.addInput(_VectorMath_003, 0);
		var _GetObjectProperty_015 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_015.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectProperty_015.addInput(new armory.logicnode.StringNode(this, "m_speed"), 0);
		_GetObjectProperty_015.addOutputs([_VectorMath_004]);
		_GetObjectProperty_015.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_VectorMath_004.addInput(_GetObjectProperty_015, 0);
		_VectorMath_004.addOutputs([_SeparateXYZ_004]);
		_SeparateXYZ_004.addInput(_VectorMath_004, 0);
		_SeparateXYZ_004.addOutputs([_Vector_005]);
		_SeparateXYZ_004.addOutputs([_Vector_005]);
		_SeparateXYZ_004.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Vector_005.addInput(_SeparateXYZ_004, 0);
		_Vector_005.addInput(_SeparateXYZ_004, 1);
		var _Math_004 = new armory.logicnode.MathNode(this);
		_Math_004.property0 = "Add";
		_Math_004.property1 = "false";
		var _SeparateXYZ_005 = new armory.logicnode.SeparateVectorNode(this);
		var _GetRBVelocity = new armory.logicnode.GetVelocityNode(this);
		_GetRBVelocity.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetRBVelocity.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_GetRBVelocity.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_GetRBVelocity.addOutputs([_SeparateXYZ_005]);
		_GetRBVelocity.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_SeparateXYZ_005.addInput(_GetRBVelocity, 0);
		_SeparateXYZ_005.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_005.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_005.addOutputs([_Math_004]);
		_Math_004.addInput(_SeparateXYZ_005, 2);
		_Math_004.addInput(new armory.logicnode.FloatNode(this, -0.5), 0);
		_Math_004.addOutputs([_Vector_005]);
		_Vector_005.addInput(_Math_004, 0);
		_Vector_005.addOutputs([_SetRBVelocity]);
		_SetRBVelocity.addInput(_Vector_005, 0);
		_SetRBVelocity.addInput(new armory.logicnode.VectorNode(this, 1.0, 1.0, 1.0), 0);
		_SetRBVelocity.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetRBVelocity.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetRBVelocity.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetObjectProperty_021.addOutputs([_SetRBVelocity]);
		_OutputSequence_001.addOutputs([_SetObjectProperty_021]);
		_SetObjectProperty_016.addInput(_OutputSequence_001, 0);
		_SetObjectProperty_016.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_016.addInput(new armory.logicnode.StringNode(this, "dir"), 0);
		var _Vector_004 = new armory.logicnode.VectorNode(this);
		_Vector_004.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector_004.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector_004.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector_004.addOutputs([_SetObjectProperty_016]);
		_SetObjectProperty_016.addInput(_Vector_004, 0);
		_SetObjectProperty_016.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetObjectProperty_014 = new armory.logicnode.SetPropertyNode(this);
		var _Branch_004 = new armory.logicnode.BranchNode(this);
		var _OnUpdate_004 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_004.property0 = "Update";
		_OnUpdate_004.addOutputs([_Branch_004]);
		_Branch_004.addInput(_OnUpdate_004, 0);
		var _Compare_002 = new armory.logicnode.CompareNode(this);
		_Compare_002.property0 = "Equal";
		_Compare_002.property1 = 9.999999747378752e-05;
		var _RayCast = new armory.logicnode.CastPhysicsRayNode(this);
		var _GetObjectLocation = new armory.logicnode.GetLocationNode(this);
		_GetObjectLocation.addInput(new armory.logicnode.ObjectNode(this, "Player"), 0);
		var _VectorMath_008 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_008.property0 = "Add";
		_VectorMath_008.property1 = false;
		_VectorMath_008.addInput(_GetObjectLocation, 0);
		var _VectorMath_007 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_007.property0 = "MultiplyFloats";
		_VectorMath_007.property1 = false;
		var _VectorMath_006 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_006.property0 = "MultiplyFloats";
		_VectorMath_006.property1 = false;
		var _TransformtoVector_002 = new armory.logicnode.VectorFromTransformNode(this);
		_TransformtoVector_002.property0 = "Up";
		var _GetObjectTransform_001 = new armory.logicnode.GetTransformNode(this);
		_GetObjectTransform_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectTransform_001.addOutputs([_TransformtoVector_002]);
		_TransformtoVector_002.addInput(_GetObjectTransform_001, 0);
		_TransformtoVector_002.addOutputs([_VectorMath_006]);
		_TransformtoVector_002.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_TransformtoVector_002.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_VectorMath_006.addInput(_TransformtoVector_002, 0);
		_VectorMath_006.addInput(new armory.logicnode.FloatNode(this, -1.0), 0);
		_VectorMath_006.addOutputs([_VectorMath_007]);
		_VectorMath_007.addInput(_VectorMath_006, 0);
		var _Float_010 = new armory.logicnode.FloatNode(this);
		_Float_010.addInput(new armory.logicnode.FloatNode(this, 2.5), 0);
		_Float_010.addOutputs([_VectorMath_007]);
		_VectorMath_007.addInput(_Float_010, 0);
		_VectorMath_007.addOutputs([_VectorMath_008]);
		_VectorMath_008.addInput(_VectorMath_007, 0);
		_VectorMath_008.addOutputs([_RayCast]);
		_GetObjectLocation.addOutputs([_RayCast, _VectorMath_008]);
		_RayCast.addInput(_GetObjectLocation, 0);
		_RayCast.addInput(_VectorMath_008, 0);
		_RayCast.addInput(new armory.logicnode.IntegerNode(this, 1), 0);
		_RayCast.addOutputs([_Compare_002]);
		_RayCast.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_RayCast.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_Compare_002.addInput(_RayCast, 0);
		var _Null = new armory.logicnode.NoneNode(this);
		_Null.addOutputs([_Compare_002]);
		_Compare_002.addInput(_Null, 0);
		_Compare_002.addOutputs([_Branch_004]);
		_Branch_004.addInput(_Compare_002, 0);
		_Branch_004.addOutputs([_SetObjectProperty_014]);
		var _SetObjectProperty_015 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_015.addInput(_Branch_004, 1);
		_SetObjectProperty_015.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_015.addInput(new armory.logicnode.StringNode(this, "isGrounded"), 0);
		var _Boolean_008 = new armory.logicnode.BooleanNode(this);
		_Boolean_008.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_Boolean_008.addOutputs([_SetObjectProperty_015]);
		_SetObjectProperty_015.addInput(_Boolean_008, 0);
		_SetObjectProperty_015.addOutputs([new armory.logicnode.NullNode(this)]);
		_Branch_004.addOutputs([_SetObjectProperty_015]);
		_SetObjectProperty_014.addInput(_Branch_004, 0);
		_SetObjectProperty_014.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetObjectProperty_014.addInput(new armory.logicnode.StringNode(this, "isGrounded"), 0);
		var _Boolean_009 = new armory.logicnode.BooleanNode(this);
		_Boolean_009.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_Boolean_009.addOutputs([_SetObjectProperty_014]);
		_SetObjectProperty_014.addInput(_Boolean_009, 0);
		_SetObjectProperty_014.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetCanvasProgressBar = new armory.logicnode.CanvasSetPBNode(this);
		_SetCanvasProgressBar.addInput(new armory.logicnode.NullNode(this), 0);
		_SetCanvasProgressBar.addInput(new armory.logicnode.StringNode(this, "staminabar"), 0);
		var _Math_003 = new armory.logicnode.MathNode(this);
		_Math_003.property0 = "Round";
		_Math_003.property1 = "false";
		var _GetObjectProperty_008 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_008.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetObjectProperty_008.addInput(new armory.logicnode.StringNode(this, "stamina"), 0);
		_GetObjectProperty_008.addOutputs([_Math_003]);
		_GetObjectProperty_008.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Math_003.addInput(_GetObjectProperty_008, 0);
		_Math_003.addOutputs([_SetCanvasProgressBar]);
		_SetCanvasProgressBar.addInput(_Math_003, 0);
		_SetCanvasProgressBar.addInput(new armory.logicnode.IntegerNode(this, 100), 0);
		_SetCanvasProgressBar.addOutputs([new armory.logicnode.NullNode(this)]);
	}
}